### ISSUE TITLE
Headless server crashes when inviting user after opening a world template, or loading a world from URL

### ISSUE THREAD

**Issue by stiefeljackal** [Yellow-Dog-Man/Resonite-Issues#1196]
### Describe the bug?

When starting up the headless server and having access to enter commands in the terminal, entering the command `startWorldTemplate <Grid|Platform|Blank>` and then entering an `invite` command will cause the headless server to crash entirely.

### To Reproduce

1. Startup the Headless and wait for command access.
2. Enter `startWorldTemplate` followed by either `Grid`, `Platform`, or `Blank`, **OR** enter `startWorldURL` followed by the `resrec` of a world.
3. Enter `invite` followed by any valid Resonite user.

### Expected behavior

An invitation should be sent to the user where:

* `startWorldTemplate` - The user can join the created world that used either the grid, platform, or blank template.
* `startWorldURL` - The user can join the world loaded from the `resrec`.

### Screenshots

<img width="920" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/1825a92b-f37d-47c7-9975-24331585ba88">

### Resonite Version Number

2024.1.19.687

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[resheadless - 2024.1.19.687 - 2024-01-19 13_53_56.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13993247/resheadless.-.2024.1.19.687.-.2024-01-19.13_53_56.log)

### Additional Context

The static `CoroutineManager` instance seems to be null when the extension method `CreateInviteMessage` is called.

### Reporters

StiefelJackal
Discord: tiky / GitHub: @ticpu

**Comment by bredo228** [comment]
> Can you please double-check, and confirm that this issue occurs on Windows too, @stiefeljackal?

Was unable to reproduce on Windows. Build 2024.1.19.687

[ERIS - 2024.1.19.687 - 2024-01-20 08_45_54.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13993812/ERIS.-.2024.1.19.687.-.2024-01-20.08_45_54.log)

**Comment by stiefeljackal** [comment]
Reviewed on Windows and can confirm that this error does not occur within Headless on Windows.

[JACKAL_MK2 - 2024.1.19.687 - 2024-01-19 14_40_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13993788/JACKAL_MK2.-.2024.1.19.687.-.2024-01-19.14_40_21.log)

**Comment by stiefeljackal** [comment]
Tried the `resrec` present in the above issue and another `resrec` and found both of them to experience the same behavior as if starting up a world with a preset:

[resheadless - 2024.1.19.687 - 2024-01-19 17_38_53.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995306/resheadless.-.2024.1.19.687.-.2024-01-19.17_38_53.log)
[resheadless - 2024.1.19.687 - 2024-01-19 17_35_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995307/resheadless.-.2024.1.19.687.-.2024-01-19.17_35_50.log)

Worlds started up via the config will still function as normal when you invite a Resonite user via the terminal as found in these logs:


[resheadless - 2024.1.19.687 - 2024-01-19 17_50_04.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995353/resheadless.-.2024.1.19.687.-.2024-01-19.17_50_04.log)
[resheadless - 2024.1.19.687 - 2024-01-19 17_43_09.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995354/resheadless.-.2024.1.19.687.-.2024-01-19.17_43_09.log)

**Comment by bredo228** [comment]
Linux:
StartWorldUrl - Crash
[Linux- StartWorldUrl.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995417/Linux-.StartWorldUrl.log)

StartWorldTemplate - Crash
[Linux - StartWorldTemplate.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995418/Linux.-.StartWorldTemplate.log)

Windows:
StartWorldUrl - Functions as intended
[Windows - StartWorldUrl.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995432/Windows.-.StartWorldUrl.log)


StartWorldTemplate - Functions as intended
[Windows - StartWorldTemplate.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13995434/Windows.-.StartWorldTemplate.log)

**Comment by stiefeljackal** [comment]
Updated the Issue body to include steps and expected behavior for `startWorldURL`.

**Comment by shiftyscales** [comment]
Is this issue still relevant / does this issue still occur following the .NET 9 upgrade to the headless, @stiefeljackal?

**Comment by stiefeljackal** [comment]
@shiftyscales I will verify tonight.

**Comment by shiftyscales** [comment]
Thank you. :)

**Comment by bredo228** [comment]
Have managed to reproduce on Beta 2025.1.30.1401.

[testheadless - 2025.1.30.1401 - 2025-02-04 12_27_28.log](https://github.com/user-attachments/files/18649293/testheadless.-.2025.1.30.1401.-.2025-02-04.12_27_28.log)

[new 6.txt](https://github.com/user-attachments/files/18649299/new.6.txt)

**Comment by stiefeljackal** [comment]
@shiftyscales What @bredo228 provided is only for `startWorldTemplate`. I am verifying `startWorldURL` now, so please allow me to submit those logs since I mentioned that I would verify this issue.

**Comment by shiftyscales** [comment]
Certainly, @stiefeljackal - I removed the "needs more information" tag specifically because the initial request was to determine if this issue is still relevant / if there is anything actionable here- and the above post has indicated there is.

If you have additional information to submit- then by all means- please do. It is appreciated.

**Comment by stiefeljackal** [comment]
`startWorldURL` is still facing this exact issue as of `2025.1.30.1401`.

* Log file: [headless - 2025.1.30.1401 - 2025-02-04 00_44_08.log](https://github.com/user-attachments/files/18649827/headless.-.2025.1.30.1401.-.2025-02-04.00_44_08.log)

* Headless Software CLI: [reso_headless_cli_startWorldURL_Command_Bug.txt](https://github.com/user-attachments/files/18649829/reso_headless_cli_startWorldURL_Command_Bug.txt)

**Comment by Hayden-Fluff** [comment]
I just experienced this, what I did was open the world "The Navy Seal" (resrec:///U-1NjOEykfqEq/R-2f910d2a-1626-49da-a320-04a287086bfa), then invited myself using the command `invite Hayden`, and the entire headless process crashed.

Here's what the CLI gave me when I ran the command

```
The Navy Seal>invite Hayden
Cannot yield to world, origin CoroutineManager is null!

   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Error(String message, Boolean stackTrace) in D:\Workspace\Everion\FrooxEngine\Elements.Core\UniLog.cs:line 78
   at FrooxEngine.NextUpdate.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine)
   at FrooxEngine.EngineSkyFrostExtensions.CreateInviteMessage(UserMessages userMessages, World world)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.EngineSkyFrostExtensions.CreateInviteMessage(UserMessages userMessages, World world)
   at FrooxEngine.Headless.HeadlessCommands.<>c.<<SetupCommonCommands>b__0_4>d.MoveNext() in D:\Workspace\Everion\FrooxEngine\Headless\Commands\HeadlessCommands.cs:line 119
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.Headless.HeadlessCommands.<>c.<SetupCommonCommands>b__0_4(CommandHandler h, World world, Contact friend, List`1 args)
   at FrooxEngine.Headless.ContactCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\Workspace\Everion\FrooxEngine\Headless\Commands\ContactCommand.cs:line 36
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.Headless.ContactCommand.<>c__DisplayClass0_0.<.ctor>b__0(CommandHandler handler, World world, List`1 args)
   at FrooxEngine.Headless.GenericCommand.Invoke(CommandHandler handler, World world, List`1 args) in D:\Workspace\Everion\FrooxEngine\Headless\Commands\GenericCommand.cs:line 48
   at FrooxEngine.Headless.CommandHandler.ProcessCommands() in D:\Workspace\Everion\FrooxEngine\Headless\Commands\CommandHandler.cs:line 114
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled Exception:

System.Exception: Cannot yield to world, origin CoroutineManager is null!
   at FrooxEngine.NextUpdate.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.Exception: Cannot yield to world, origin CoroutineManager is null!
   at FrooxEngine.NextUpdate.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

This is on Linux running through Docker, I'm not sure where to find the full log files.

**Comment by Frooxius** [comment]
Merged fix in 2025.11.18.1216! Thanks!
