### ISSUE TITLE
Headless tries (And fails) to connect to Discord and Steam

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#2022]
### Describe the bug?

similar issue as reported in #2020. The Headless client tries to connect to Discord and Steam but if it's in a datacenter or dedicated matching it will fail.

### To Reproduce

Boot up a headless and wait for it to try to connect to Discord or Steam

### Expected behavior

The headless server doesn't try to connect to Discord or Steam.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/1a3b7326-9e75-43b0-a3d8-1b91f9ac2a32)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[84cc5bdd63e6 - 2024.5.7.505 - 2024-05-10 06_38_16.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15279296/84cc5bdd63e6.-.2024.5.7.505.-.2024-05-10.06_38_16.log)
[84cc5bdd63e6 - 2024.5.7.505 - 2024-05-10 19_28_16.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15279297/84cc5bdd63e6.-.2024.5.7.505.-.2024-05-10.19_28_16.log)
[84cc5bdd63e6 - 2024.5.7.505 - 2024-05-10 19_31_18.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15279298/84cc5bdd63e6.-.2024.5.7.505.-.2024-05-10.19_31_18.log)
[84cc5bdd63e6 - 2024.5.7.505 - 2024-05-10 04_40_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15279299/84cc5bdd63e6.-.2024.5.7.505.-.2024-05-10.04_40_36.log)

### Reporters

ExoTheWicker

**Comment by ProbablePrime** [comment]
Will grab

**Comment by ProbablePrime** [comment]
#1522 is highly related to this as it deals with when and when we should not do discord/steam "things".

Due to this I'll work on them both at the same time.

**Comment by ExoTheWicker** [comment]
#2554 Is also related.

**Comment by ProbablePrime** [comment]
Will be solved as a part of #2554

**Comment by ProbablePrime** [comment]
Steam fixes are coming soon.

As for Discord, This no longer happens. Instead you get:
```
11:08:49 AM.244 Exception initializing connector: FrooxEngine.Interfacing.DiscordConnector
DiscordGameSDKWrapper.ResultException: InternalError
   at DiscordGameSDKWrapper.Discord..ctor(Int64 clientId, UInt64 flags)
   at FrooxEngine.Interfacing.DiscordConnector.Initialize(PlatformInterface platformInterface)
   at FrooxEngine.PlatformInterface.Initialize(Engine engine)
```

Which i can't really debug because there is no context available from Discord's SDK. Discord isn't supporting this SDK anymore either.

So I opened #4147 but we can't update that till we're off Unity. So... we'll just have to leave this open
