### ISSUE TITLE
Headless crashes with Discord related errors

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#2554]
### Describe the issue.

After playing with .NET 8.0 headless for a while, I get this error and crash.
This error appears in the console but does not appear to be logged.
This error has occurred twice, the first time while fiddling with Flux and the second time while playing with a bunch of items.

```
Process terminated. A callback was made on a garbage collected delegate of type 'DiscordGameSDKWrapper!DiscordGameSDKWrapper.ActivityManager+FFIMethods+UpdateActivityCallback::Invoke'.
   at FrooxEngine.Interfacing.DiscordConnector.Update()
   at FrooxEngine.PlatformInterface.Update()
   at FrooxEngine.Engine.UpdateStep()
   at FrooxEngine.Engine.RunUpdateLoop()
   at FrooxEngine.StandaloneFrooxEngineRunner.UpdateLoop()
```

### To Reproduce

NET 8.0 headless without any configurations and connect to that session.
After playing with that session for a few minutes, suddenly this error occurs.

### Expected behavior

The session continues without error.

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ORANGELESSEQ - 2024.7.12.12 - 2024-07-12 23_32_30.log](https://github.com/user-attachments/files/16196255/ORANGELESSEQ.-.2024.7.12.12.-.2024-07-12.23_32_30.log)
[ORANGELESSEQ - 2024.7.12.12 - 2024-07-12 23_38_31.log](https://github.com/user-attachments/files/16196256/ORANGELESSEQ.-.2024.7.12.12.-.2024-07-12.23_38_31.log)

### Reporters

orange3134

**Comment by orange3134** [comment]
I have confirmed that this also occurs on 2024.7.12.933.
The same error appears in the console, although it is not shown in the log.
[ORANGELESSEQ - 2024.7.12.933 - 2024-07-13 01_25_24.log](https://github.com/user-attachments/files/16196882/ORANGELESSEQ.-.2024.7.12.933.-.2024-07-13.01_25_24.log)

**Comment by shiftyscales** [comment]
Assigning @Frooxius.

**Comment by ExoTheWicker** [comment]
This is related to #2022

**Comment by Frooxius** [comment]
There's actually PR from @Geenz internally that should fix this by switching to C# 11 as the language. We need to verify if this breaks other things, due to it being global project-wide change, but it should fix this.

**Comment by charlie-sans** [comment]
in the meantime, is there anyway to get around this issue?

**Comment by Frooxius** [comment]
I've merged the fix in 2024.9.16.715, thanks for report!

**Comment by shiftyscales** [comment]
@charlie-sans has reported in #2988 that this issue is still occurring as of `Beta 2024.9.16.1105`. Are you still experiencing this issue as well, @orange3134?

**Comment by shiftyscales** [comment]
There are still a few other related issues in this general area @ProbablePrime was previously looking into- #1522 / #2022.

**Comment by Nytra** [comment]
I am encountering this with the .NET 9 headless on Windows 11

```
Process terminated. A callback was made on a garbage collected delegate of type 'DiscordGameSDKWrapper!DiscordGameSDKWrapper.ActivityManager+FFIMethods+UpdateActivityCallback::Invoke'.
   at FrooxEngine.Interfacing.DiscordConnector.Update()
   at FrooxEngine.PlatformInterface.Update()
   at FrooxEngine.Engine.UpdateStep()
   at FrooxEngine.Engine.RunUpdateLoop()
   at FrooxEngine.StandaloneFrooxEngineRunner.UpdateLoop()
```

**Comment by ProbablePrime** [comment]
All I'm getting on Linux now is:
```
11:08:49 AM.244 Exception initializing connector: FrooxEngine.Interfacing.DiscordConnector
DiscordGameSDKWrapper.ResultException: InternalError
   at DiscordGameSDKWrapper.Discord..ctor(Int64 clientId, UInt64 flags)
   at FrooxEngine.Interfacing.DiscordConnector.Initialize(PlatformInterface platformInterface)
   at FrooxEngine.PlatformInterface.Initialize(Engine engine)
```

@Nytra has any behavior changed for you since your last post.

**Comment by Nytra** [comment]
@ProbablePrime I believe the crash still happens. I have been deleting DiscordGameSDKWrapper.dll to stop it from happening.

**Comment by ProbablePrime** [comment]
Oh ok. Hmm.

Perhaps we should default the discord stuff to off on headlesses.

Oh, You can use: `disallowedPlatformInterfaces` in a Config.json file to disable discord now too.

**Comment by XDelta** [comment]
I've not seen the crashing occurring here on a linux headless and I am not removing any of the existing files, it has just being adding an error in the log and continues. I just see the same exception that you have posted prime.

**Comment by ProbablePrime** [comment]
marking as done, I've done all I can till the splittening is over now :D
