### ISSUE TITLE
Headless Does Not Load Worlds After Update

### ISSUE THREAD

**Issue by pysicist** [Yellow-Dog-Man/Resonite-Issues#2636]
### Describe the bug?

Updated the headless server to the latest version on windows. Tried to start my usual hosted world and the server closed without getting to launching the world. Tried to load a default grid space and that threw the same error and closed the dialog window. I have no mods installed on the headless.

### To Reproduce

Unsure if can be preproduced outside my system but can provide my server files for examination.

### Expected behavior

Server started as normal and loaded world and grid spaces without issue before update.

### Resonite Version Number

Beta 2024.7.20.94

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

11:31:13 PM.801	AppPath: D:\SteamCMD\steamapps\common\Resonite\Headless
DataPath: D:\SteamCMD\steamapps\common\Resonite\Headless\Data
CachePath: D:\SteamCMD\steamapps\common\Resonite\Headless\Cache
11:31:13 PM.817	Initializing App: Beta 2024.7.20.94
Platform: Windows
HeadDevice: Headless
IsAOT: False
OS: Microsoft Windows 11 Home
CPU: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
GPU: NVIDIA GeForce GTX 860M
PhysicalCores: 4
MemoryBytes: 15.89 GB
VRAMBytes: 2.00 GB
MaxTextureSize: 16384
IsGPUTexturePOTByteAligned: True
UsingLinearSpace: False
XR Device Name: 
XR Device Model: 
StereoRenderingMode: 
Max GC Generation: 2, IsLittleEndian: True
System.Numerics.Vectors HW accelerated: True, Vector<float>.Count: 8
Brotli native encoding/decoding supported: True
11:31:13 PM.832	Supported Texture Formats: Unknown, Alpha8, R8, RGB24, ARGB32, RGBA32, BGRA32, RGB565, RGBAHalf, ARGBHalf, RHalf, RGHalf, RGBAFloat, ARGBFloat, RFloat, RGFloat, BC1, BC2, BC3, BC4, BC5, BC6H, BC7, ETC2_RGB, ETC2_RGBA1, ETC2_RGBA8, ASTC_4x4, ASTC_5x5, ASTC_6x6, ASTC_8x8, ASTC_10x10, ASTC_12x12
11:31:13 PM.832	Processing startup commands...
11:31:13 PM.832	Scanning locales...
11:31:13 PM.832	Available locales: cs, de, en, en-gb, eo, es, et, fi, fr, hu, is, ja, ko, nl, no, pl, pt-br, ru, sv, th, tr, zh-cn, zh-tw
11:31:13 PM.848	Loading Config.json...
11:31:13 PM.848	Computing compatibility hash...
11:31:13 PM.848	Engine WebProxy initialization failed.
11:31:13 PM.848	Initializing FrooxEngine...
11:31:14 PM.223	FreeImage Version: 3.18.1
11:31:14 PM.223	BepuPhysics Version: 2.4.0.2-ydm-0.1.6
11:31:14 PM.223	FreeType Version: 2.10.4
11:31:14 PM.238	Opus Version: libopus 1.3.1-138-g07376903
11:31:14 PM.270	Supported 3D model formats: meshx, 3d, 3ds, 3mf, ac, ac3d, acc, amf, ase, ask, assbin, b3d, blend, bsp, bvh, cob, csm, dae, dxf, enff, fbx, glb, gltf, hmp, ifc, ifczip, iqm, irr, irrmesh, lwo, lws, lxo, md2, md3, md5anim, md5camera, md5mesh, mdc, mdl, mesh, mesh.xml, mot, ms3d, ndo, nff, obj, off, ogex, pk3, ply, pmx, prj, q3o, q3s, raw, scn, sib, smd, step, stl, stp, ter, uc, vta, x, x3d, x3db, xgl, xml, zae, zgl
11:31:14 PM.270	Supported point cloud formats: pts, las, laz
11:31:14 PM.270	Supported image formats: bmp, ico, jpg, jif, jpeg, jpe, jng, koa, iff, lbm, mng, pbm, pcd, pcx, pgm, png, ppm, ras, tga, targa, tif, tiff, wap, wbmp, wbm, psd, psb, cut, xbm, xpm, dds, gif, hdr, g3, sgi, rgb, rgba, bw, exr, j2k, j2c, jp2, pfm, pct, pict, pic, 3fr, arw, bay, bmq, cap, cine, cr2, crw, cs1, dc2, dcr, drf, dsc, dng, erf, fff, ia, iiq, k25, kc2, kdc, mdc, mef, mos, mrw, nef, nrw, orf, pef, ptx, pxn, qtk, raf, raw, rdc, rw2, rwl, rwz, sr2, srf, srw, sti, x3f, webp, jxr, wdp, hdp
11:31:14 PM.270	Supported audio formats: wav, wave, flac, fla, ogg, aiff, aif, aifc
11:31:14 PM.270	Supported video formats: mp4, mpeg, avi, mov, mpg, mkv, flv, webm, mts, 3gp, bik, m2v, m2s, wmv, m3u8, m3u, pls, ogv, m4a, mp3, mpeg3, aac, ac3, aif, aiff, ape, au, it, mka, mod, mp1, mp2, opus, s3m, sid, w64, wma, xm, nsf, nsfe, gbs, vgm, vgz, spc, gym
11:31:14 PM.270	Supported font formats: ttf, otf, ttc, otc, woff
11:31:14 PM.270	Supported document formats: pdf
11:31:14 PM.270	Supported subtitle formats: srt, sub, sub, ssa, ttml, vtt
11:31:14 PM.285	Scanning assemblies
11:31:14 PM.395	Exception getting types from assembly FrooxEngine.Store, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at FrooxEngine.EngineInitializer.<>c__DisplayClass4_0.<InitializeFrooxEngine>b__0(Assembly assembly) in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 67

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Error(String message, Boolean stackTrace) in D:\Workspace\Everion\FrooxEngine\Elements.Core\UniLog.cs:line 59
   at FrooxEngine.EngineInitializer.<>c__DisplayClass4_0.<InitializeFrooxEngine>b__0(Assembly assembly) in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 67
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
11:31:14 PM.660	Data Model Assembly: SkyFrost.Base.Models, Type Count: 4 (total: 193, Compatibility Hash: pi+qiFhdImZ42rvy8ybJnQ==, Type: Core)
11:31:14 PM.676	Data Model Assembly: Elements.Core, Type Count: 51 (total: 558, Compatibility Hash: 3XaWAwwz7srqNA3kWPtREA==, Type: Core)
11:31:14 PM.676	Data Model Assembly: Elements.Assets, Type Count: 84 (total: 440, Compatibility Hash: 24V+N5WFzjcN116FRTKEug==, Type: Core)
11:31:14 PM.707	Data Model Assembly: ProtoFlux.Nodes.FrooxEngine, Type Count: 155 (total: 784, Compatibility Hash: w5eT+VlkgtJngh/EZmrhfg==, Type: Core)
11:31:14 PM.832	Data Model Assembly: ProtoFlux.Nodes.Core, Type Count: 10 (total: 2172, Compatibility Hash: XxMkLAc6ulemxNEOJo7IOQ==, Type: Core)
11:31:16 PM.270	Data Model Assembly: ProtoFluxBindings, Type Count: 5958 (total: 6036, Compatibility Hash: bbNCf+ejH9n1KOZmxNbCgg==, Type: Core)
11:31:17 PM.973	Data Model Assembly: FrooxEngine, Type Count: 2357 (total: 10479, Compatibility Hash: Z3spa0NTUY8YPCy/7tW3Cw==, Type: Core)
11:31:17 PM.973	Exception initializing FrooxEngine:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at FrooxEngine.EngineInitializer.<>c__DisplayClass4_0.<InitializeFrooxEngine>b__0(Assembly assembly) in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 80
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.EngineInitializer.<InitializeFrooxEngine>d__4.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.Engine.<InitializeFrooxEngine>d__327.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Engine.cs:line 764

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Error(String message, Boolean stackTrace) in D:\Workspace\Everion\FrooxEngine\Elements.Core\UniLog.cs:line 59
   at FrooxEngine.Engine.<InitializeFrooxEngine>d__327.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Engine.cs:line 764
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
   at FrooxEngine.EngineInitializer.<InitializeFrooxEngine>d__4.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 96
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetException(IEnumerable`1 exceptions)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.CompleteBlockOncePossible()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
11:31:17 PM.989	Unhandled Exception:

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at FrooxEngine.EngineInitializer.<>c__DisplayClass4_0.<InitializeFrooxEngine>b__0(Assembly assembly) in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 80
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.EngineInitializer.<InitializeFrooxEngine>d__4.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Initialization\EngineInitializer.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.Engine.<InitializeFrooxEngine>d__327.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Engine.cs:line 769
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.Engine.<Initialize>d__319.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Engine.cs:line 528
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.StandaloneFrooxEngineRunner.<Initialize>d__36.MoveNext() in D:\Workspace\Everion\FrooxEngine\FrooxEngine\Engine\StandaloneFrooxEngineRunner.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.Headless.Program.<Main>d__15.MoveNext() in D:\Workspace\Everion\FrooxEngine\HeadlessLegacy\Program.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.Headless.Program.<Main>(String[] args)

### Reporters

@pysicist

**Comment by ShrikeAlvaron** [comment]
There’s a newer version out now that fixes the cloud issues, 2024.7.20.1115.  Older versions will no longer work at all due to them causing the cloud issues in the first place, so make sure you update to this one and try it again to see if that fixes it.

**Comment by pysicist** [comment]
I have updated it. That seems to fix the launching problem. I loads worlds now, but i cannot connect to it in resonite. It says it can't find the world name.

**Comment by pysicist** [comment]
I had a few other people try in resonite as well and they were getting the same error.

**Comment by XDelta** [comment]
Can you provide an updated log?

**Comment by pysicist** [comment]
Well I'm not sure what to say now... It seems to have fixed itself? I just retried rebooting the computer the server was on and restart the server, invited myself from console and could connect right off the bat. Thanks for your time Shrike, appreciate you looking into this, but it seems like it is working at the moment.

**Comment by pysicist** [comment]
Do you still want a log XDelta?

**Comment by XDelta** [comment]
Just if you still were getting an error from trying to connect. Although you could probably grab that section from a previous log. May have been related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2641 as that affected people joining some sessions earlier today.

**Comment by pysicist** [comment]
I'm seeing a lot of this:
9:37:37 PM.611	LNL_Listener NetworkError, endPoint: 0.0.0.1:38842, socketError: NetworkUnreachable

**Comment by XDelta** [comment]
Sounds like that issue previously mentioned

**Comment by pysicist** [comment]
Yeah I'm reading into it now, it's definitely sounding very similar. Thanks for linking it that seems to be the second issue resolved. Hopefully.

**Comment by shiftyscales** [comment]
Please let us know if you are still having issues on the latest version, @pysicist. If you are, please include an updated log file from the host / client attempting to connect.

Otherwise, this issue can be closed out.
