### ISSUE TITLE
Cannot connect to a Linux .NET Headress session with a Direct IP

### ISSUE THREAD

**Issue by sjsanjsrh** [Yellow-Dog-Man/Resonite-Issues#2651]
### Describe the bug?

A server that worked fine in mono would have switched to .NET. It is not reachable from the direct IP, but is reachable from the outside.

### To Reproduce

resrec:///S-U-SinduyHDL:TheVoid

### Expected behavior

 Headless Environment
Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-116-generic x86_64)
Microsoft.NETCore.App 8.0.7 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

### Resonite Version Number

Beta 2024.7.22.1319

### What Platforms does this occur on?

Windows, Linux

### Log Files

[HeadLessServerLogFile](https://github.com/user-attachments/files/16346966/mini-server.-.2024.7.22.1319.-.2024-07-23.03_34_02.log)
[ClientLogFile](https://github.com/user-attachments/files/16346967/DESKTOP-7Q77KOJ.-.2024.7.22.1319.-.2024-07-23.12_32_41.log)

**Comment by Frooxius** [comment]
- What is the network topology? Are they both on local network? 
- How are you getting the direct IP and port to connect to?

In the log, I noticed that the server is hosting on 172.30.1.98 on port 49917, but the client is trying to connect to port 40859 instead.

It seems like that might be the main cause - the port is mismatched.

**Comment by sjsanjsrh** [comment]
This log is accessed from an invitation from the HeadLess server.
Both devices are on the LAN and attempt to reach the resrec address.

**Comment by sjsanjsrh** [comment]
@Frooxius It's trying to access it by SessionId, but it doesn't seem to know the correct port.

Logs from the Headless side of another test.
```
NetworkInitStart
LNL Listener for World  (Handle: 2. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: True, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0.0258754, running on 0.0.0.0, port 55749
LNL Listener for World  (Handle: 2. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: True, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0.0338168, running on 172.30.1.98, port 42293
```

This is the client side log
```
PM 8:01:22.601 LNL Connection Disconnected: 172.30.1.98:38857, reason: ConnectionFailed, socketErrorCode: Success
PM 8:01:22.601 Connection to lnl://172.30.1.98:38857/ closed: Peer Disconnected
PM 8:01:22.601 Connection lnl://172.30.1.98:38857/ was unsuccessful, trying next available option
PM 8:01:22.602 LNL Connection for Address: lnl://172.30.1.98:38857/, World  (Handle: 4. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 18.24183 on port 58070. LocalBindIP: 172.30.1.102
PM 8:01:22.602 Connecting to: lnl://172.30.1.98:38857/
PM 8:01:22.602 Establishing direct IP connection to lnl://172.30.1.98:38857/. Don't route: True
PM 8:01:22.602 Direct IP connection peer. ID: 0, State: Outgoing, Address: 172.30.1.98
```

In this test, connecting directly to lnl://172.30.1.98:42293 works fine.

**Comment by sjsanjsrh** [comment]
I am currently using the forcePort option to fix the 41863 port for Headless.

From a certain release onwards, it is no longer possible to connect to the ‘Open World’ flux node by entering the lnl link of the server on that local network. Although this method was previously used as a workaround for this issue, OnOpenFail is now triggered. However, if I paste the this link into the clipboard, it will open.
<img width="1199" height="534" alt="Image" src="https://github.com/user-attachments/assets/3c22d0ab-2500-4f17-b3d0-3bb1da2e4d7f" />


When attempting to access via an invitation link or resrec link, it attempts to connect to an incorrect port as follows.
```
ℹ️오후 4:26:52.642 (FPS: 180):	Opening world. URI's: lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-U-SinduyHDL:TheVoid, lnl://172.30.1.98:35757/
ℹ️오후 4:26:52.645 (FPS: 180):	Joining session: lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-U-SinduyHDL:TheVoid,lnl://172.30.1.98:35757/

   at string SyncProxy<System.String System.Environment:get_StackTrace()>(?)
   at void DMD<DMD<>?50516257::Elements.Core.UniLog::Log>(?)
   at void SyncProxy<System.Void Elements.Core.UniLog:Log(System.String, System.Boolean)>(?)
   at World FrooxEngine.World.JoinSession(WorldManager manager, IEnumerable<Uri> addresses) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/World.cs:line 895
   at World FrooxEngine.WorldManager.JoinSession(IEnumerable<Uri> addresses) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/WorldManager.cs:line 160
   at World FrooxEngine.Userspace.JoinSession(IEnumerable<Uri> addresses, IWorldLink sourceLink, bool focusWhenReady) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Userspace/Userspace/WorldManagement.cs:line 568
   at async Task<World> FrooxEngine.Userspace.OpenWorldInternal(WorldStartSettings startInfo) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Userspace/Userspace/WorldManagement.cs:line 248
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<World> FrooxEngine.Userspace.OpenWorldInternal(WorldStartSettings startInfo)
   at async Task<World> FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo)+(?) => { } in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Userspace/Userspace/WorldManagement.cs:line 199
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<World> FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo)+() => { }
   at Task<T> FrooxEngine.CoroutineManager.StartTask<T>(Func<Task<T>> task, IUpdatable updatable) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Coroutines/CouroutineManager.cs:line 490
   at Task<T> FrooxEngine.Worker.StartTask<T>(Func<Task<T>> task) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Data Model/Base Classes/Worker.cs:line 544
   at async Task<World> FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Userspace/Userspace/WorldManagement.cs:line 199
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<World> FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo)
   at void FrooxEngine.SessionItem.OnJoin(IButton button, ButtonEventData eventData) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Userspace/Components/Friends/SessionItem.cs:line 89
   at void FrooxEngine.UIX.Button.RunPressed(ButtonEventData eventData) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/UIX/Interactions/Button.cs
   at void FrooxEngine.UIX.Button.OnPressBegin(InteractionData eventData) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/UIX/Interactions/Button.cs:line 154
   at bool FrooxEngine.UIX.InteractionElement.ProcessEvent(InteractionData eventData) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/UIX/Interactions/InteractionElement.cs:line 330
   at bool FrooxEngine.UIX.Canvas.ProcessTouchEvent(in TouchEventInfo eventInfo, List<Predicate<IUIInteractable>> filters) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/UIX/Canvas.cs:line 1099
   at void FrooxEngine.TouchSource.SendTouchEvent(ITouchable touchable, in TouchEventInfo touchInfo) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/Input/TouchSystem/TouchSource.cs:line 157
   at void FrooxEngine.TouchSource.UpdateCurrentTouchable(ITouchable touchable, in float3 point, in float3 direction, in float3 directHitPoint, bool touch) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/Input/TouchSystem/TouchSource.cs:line 141
   at RelayTouchSource FrooxEngine.PointerInteractionController.UpdatePointer(Pointer pointer, float2 axisDelta) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/Input/PointerInteractionController.cs:line 237
   at void FrooxEngine.PointerInteractionController.ProcessUserspacePointers() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Components/Input/PointerInteractionController.cs:line 183
   at void FrooxEngine.InputBindingManager.SendInputUpdateEvents(Action<IInputUpdateReceiver> action, HashSet<IInputUpdateReceiver> sentEvents) in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Input/Binding/InputBindingManager.cs:line 381
   at void FrooxEngine.InputBindingManager.Update() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Input/Binding/InputBindingManager.cs:line 215
   at bool FrooxEngine.World.RefreshStep() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/World.cs:line 1726
   at bool FrooxEngine.World.Refresh() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/World.cs:line 1384
   at void FrooxEngine.WorldManager.UpdateStep() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/WorldManager.cs:line 616
   at bool FrooxEngine.WorldManager.RunUpdateLoop() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/WorldManager.cs:line 417
   at void FrooxEngine.Engine.UpdateStep() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Engine.cs:line 1581
   at void FrooxEngine.Engine.RunUpdateLoop() in C:/Workspace/Resonite/FrooxEngine/FrooxEngine/Engine.cs:line 1343
   at void Renderite.Host.GraphicalClientRunner.UpdateLoop() in C:/Workspace/Resonite/FrooxEngine/GraphicalClient/GraphicalClientRunner.cs:line 170
   at void System.Threading.Thread.StartCallback()
ℹ️오후 4:26:52.646 (FPS: 180):	NetworkInitStart
ℹ️오후 4:26:52.646 (FPS: 180):	Network manager: FrooxEngine.LNL_Manager - priority: 0
ℹ️오후 4:26:52.646 (FPS: 180):	Network manager: FrooxEngine.SteamNetworkManager - priority: -100
ℹ️오후 4:26:52.646 (FPS: 180):	Network manager: FrooxEngine.TCP_Manager - priority: -1000
ℹ️오후 4:26:52.646 (FPS: 180):	Connecting to: lnl://172.30.1.98:35757/
ℹ️오후 4:26:52.647 (FPS: 180):	Loading from URI: resrec:///G-Resonite/Inventory/SpawnObjects/WorldLoadingIndicator
ℹ️오후 4:26:52.647 (FPS: 180):	LNL Connection for Address: lnl://172.30.1.98:35757/, World  (Handle: 5. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0.0028784 on port 53498. LocalBindIP: 0.0.0.0
ℹ️오후 4:26:52.648 (FPS: 180):	Establishing direct IP connection to lnl://172.30.1.98:35757/. Don't route: False
ℹ️오후 4:26:52.648 (FPS: 180):	Direct IP connection peer. ID: 0, State: Outgoing, Address: 172.30.1.98
ℹ️오후 4:26:52.652 (FPS: 180):	Loading object from record: Record G-Resonite:R-b3c95a4a-a0ba-4820-a61b-ec34b0ae5969, Name: WorldLoadingIndicator, Type: object, Path: Inventory\SpawnObjects, Version: Global: 1, Local: 1, UserId: U-Ryuvi, MachineId: yad361wepsph8k9fpqi6c16m5rr4isaprpwqb7wjyhfrgapppjty, AssetURI: resdb:///6c4adab1f3a16562788eeae41191b6579920
```

The following is the log when successfully connected via the Asset importer.
```
ℹ️오후 4:31:46.089 (FPS: 163):	Importing files with Asset Class Unknown:
lnl://172.30.1.98:41863/
ℹ️오후 4:31:46.089 (FPS: 163):	Opening world. URI's: lnl://172.30.1.98:41863/
ℹ️오후 4:31:46.091 (FPS: 163):	Joining session: lnl://172.30.1.98:41863/

   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Log(String message, Boolean stackTrace) in C:\Workspace\Resonite\FrooxEngine\Elements.Core\UniLog.cs:line 36
   at FrooxEngine.World.JoinSession(WorldManager manager, IEnumerable`1 addresses) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\World.cs:line 895
   at FrooxEngine.WorldManager.JoinSession(IEnumerable`1 addresses) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\WorldManager.cs:line 160
   at FrooxEngine.Userspace.JoinSession(IEnumerable`1 addresses, IWorldLink sourceLink, Boolean focusWhenReady) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Userspace\Userspace\WorldManagement.cs:line 568
   at FrooxEngine.Userspace.OpenWorldInternal(WorldStartSettings startInfo) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Userspace\Userspace\WorldManagement.cs:line 248
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.Userspace.OpenWorldInternal(WorldStartSettings startInfo)
   at FrooxEngine.Userspace.<>c__DisplayClass184_0.<<OpenWorld>b__0>d.MoveNext() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Userspace\Userspace\WorldManagement.cs:line 199
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.Userspace.<>c__DisplayClass184_0.<OpenWorld>b__0()
   at FrooxEngine.CoroutineManager.StartTask[T](Func`1 task, IUpdatable updatable) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Coroutines\CouroutineManager.cs:line 490
   at FrooxEngine.Worker.StartTask[T](Func`1 task) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Data Model\Base Classes\Worker.cs:line 544
   at FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Userspace\Userspace\WorldManagement.cs:line 199
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.Userspace.OpenWorld(WorldStartSettings startInfo)
   at FrooxEngine.UniversalImporter.ImportNetworkUrl(World world, Uri url, Transform transform) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Assets\Importing\UniversalImporter.cs:line 959
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.UniversalImporter.ImportNetworkUrl(World world, Uri url, Transform transform)
   at FrooxEngine.UniversalImporter.ImportTask(AssetClass assetClass, IEnumerable`1 files, World world, float3 position, floatQ rotation, float3 scale, Boolean silent) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Assets\Importing\UniversalImporter.cs:line 489
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at FrooxEngine.ToWorld.<>c__DisplayClass3_0.<OnCompleted>b__0(Object u) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Coroutines\ToWorld.cs:line 42
   at FrooxEngine.CoroutineManager.ExecuteAsyncQueue(SpinQueue`1 queue) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Coroutines\CouroutineManager.cs:line 402
   at FrooxEngine.CoroutineManager.ExecuteWorldQueue(Double deltaTime) in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Coroutines\CouroutineManager.cs:line 369
   at FrooxEngine.World.RefreshStep() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\World.cs:line 1735
   at FrooxEngine.World.Refresh() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\World.cs:line 1384
   at FrooxEngine.WorldManager.UpdateStep() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\WorldManager.cs:line 616
   at FrooxEngine.WorldManager.RunUpdateLoop() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\WorldManager.cs:line 417
   at FrooxEngine.Engine.UpdateStep() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Engine.cs:line 1581
   at FrooxEngine.Engine.RunUpdateLoop() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Engine.cs:line 1343
   at Renderite.Host.GraphicalClientRunner.UpdateLoop() in C:\Workspace\Resonite\FrooxEngine\GraphicalClient\GraphicalClientRunner.cs:line 170
   at System.Threading.Thread.StartCallback()
ℹ️오후 4:31:46.092 (FPS: 163):	NetworkInitStart
ℹ️오후 4:31:46.093 (FPS: 163):	Network manager: FrooxEngine.LNL_Manager - priority: 0
ℹ️오후 4:31:46.093 (FPS: 163):	Network manager: FrooxEngine.SteamNetworkManager - priority: -100
ℹ️오후 4:31:46.093 (FPS: 163):	Network manager: FrooxEngine.TCP_Manager - priority: -1000
ℹ️오후 4:31:46.095 (FPS: 163):	Connecting to: lnl://172.30.1.98:41863/
ℹ️오후 4:31:46.096 (FPS: 163):	LNL Connection for Address: lnl://172.30.1.98:41863/, World  (Handle: 4. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0.0048972 on port 58471. LocalBindIP: 0.0.0.0
ℹ️오후 4:31:46.096 (FPS: 163):	Loading from URI: resrec:///G-Resonite/Inventory/SpawnObjects/WorldLoadingIndicator
ℹ️오후 4:31:46.096 (FPS: 163):	Establishing direct IP connection to lnl://172.30.1.98:41863/. Don't route: False
ℹ️오후 4:31:46.101 (FPS: 163):	Loading object from record: Record G-Resonite:R-b3c95a4a-a0ba-4820-a61b-ec34b0ae5969, Name: WorldLoadingIndicator, Type: object, Path: Inventory\SpawnObjects, Version: Global: 1, Local: 1, UserId: U-Ryuvi, MachineId: yad361wepsph8k9fpqi6c16m5rr4isaprpwqb7wjyhfrgapppjty, AssetURI: resdb:///6c4adab1f3a16562788eeae41191b65799207e6b5004cef25c6cc7ae27284c8d.brson, Deleted: False
ℹ️오후 4:31:46.101 (FPS: 163):	Source record: Record G-Resonite:R-b3c95a4a-a0ba-4820-a61b-ec34b0ae5969, Name: WorldLoadingIndicator, Type: object, Path: Inventory\SpawnObjects, Version: Global: 1, Local: 1, UserId: U-Ryuvi, MachineId: yad361wepsph8k9fpqi6c16m5rr4isaprpwqb7wjyhfrgapppjty, AssetURI: resdb:///6c4adab1f3a16562788eeae41191b65799207e6b5004cef25c6cc7ae27284c8d.brson, Deleted: False
ℹ️오후 4:31:46.101 (FPS: 163):	Direct IP connection peer. ID: 0, State: Outgoing, Address: 172.30.1.98
```

**Comment by sjsanjsrh** [comment]
Network capture attached
[resonite.pcapng.gz](https://github.com/user-attachments/files/24523982/resonite.pcapng.gz)

**Comment by sjsanjsrh** [comment]
Based on the results of collecting broadcasts on port 12101, it appears that the local IP address and port are not included. 

[dump.tar.gz](https://github.com/user-attachments/files/27158195/dump.tar.gz)

window.bin contains data from the Windows client, including the IP:port
<img width="705" height="313" alt="Image" src="https://github.com/user-attachments/assets/f1286168-c00a-453d-a7f3-027d842d6216" />

headless.bin contains data from the Headless client, not seen IP:port
<img width="692" height="332" alt="Image" src="https://github.com/user-attachments/assets/f7d0fc9a-f7bd-4ea3-a7eb-e1a744471a0c" />
