### ISSUE TITLE
Headless RecyclableMemoryStream Crash

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#3180]
### Describe the bug?

I came home from work and noticed my headless was down.  I logged in over SSH and saw errors and it Aborted.

### To Reproduce

Unsure

### Expected behavior

Not to crash?

### Screenshots

![Image](https://github.com/user-attachments/assets/882428b7-1db0-4420-84b2-4ee41508dec1)

### Resonite Version Number

2024.11.12.1329

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The stream with Id 5702917 and Tag  is disposed.'.
   at Microsoft.IO.RecyclableMemoryStream.CheckDisposed() in D:\Workspace\Everion\FrooxEngine\Elements.Core\RecyclableMemoryStream\RecyclableMemoryStream.cs:line 811
   at Microsoft.IO.RecyclableMemoryStream.get_Length() in D:\Workspace\Everion\FrooxEngine\Elements.Core\RecyclableMemoryStream\RecyclableMemoryStream.cs:line 356
   at FrooxEngine.BinaryMessageBatch.ToString()
   at FrooxEngine.SyncMessage.Finalize()
Aborted
```

[ResoniteServer_2024.11.12.1329-2024-11-13_13_38_48.log](https://github.com/user-attachments/files/17743830/ResoniteServer_2024.11.12.1329-2024-11-13_13_38_48.log)

**Comment by troyBORG** [comment]
This was the first time I've seen the error show up.  
Only thing that changed was `ghostscript libgs9 libgs9-common` had updates in Ubuntu, and the Resonite version update...

**Comment by troyBORG** [comment]
Well restarting the headless, and letting it run all day, the issue hasn't returned.  It seems so far to of been a one time bug.  

I thought it was weird, and wanted to report it since I never know if it might be some weird bug that only pops ups randomly and might of been hard to diagnose..
