### ISSUE TITLE
Playing Audio randomly crashes net 9 headless

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3270]
### Describe the bug?

hosting a net 9 headless for building in and suddenly it just crashed. i checked the logs and everything and seemed to find  a shit ton of 
```
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildAdded(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.Slot.NewParentSlotAvailable(FrooxEngine.SyncRef`1<FrooxEngine.Slot>)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ValueChanged()
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalSetRefID(Elements.Core.RefID ByRef, System.__Canon)
   at FrooxEngine.SyncRef`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Target(System.__Canon)
   at FrooxEngine.Slot.SetParent(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.AddSlot(System.String, Boolean)
   at FrooxEngine.SlotAssets.PlayOneShot(FrooxEngine.World, Elements.Core.float3, FrooxEngine.IAssetProvider`1<FrooxEngine.AudioClip>, Single, Boolean, Single, FrooxEngine.Slot, FrooxEngine.AudioDistanceSpace, Boolean)
   at FrooxEngine.RandomAudioClipPlayerBase.PlayAtPoint(System.Collections.Generic.IList`1<ClipData>, Elements.Core.float3 ByRef)
   at FrooxEngine.ChildParentAudioClipPlayer.PlayClip(FrooxEngine.Slot, FrooxEngine.SyncList`1<ClipData>, Boolean)
   at FrooxEngine.ChildParentAudioClipPlayer.Slot_ChildRemoved(FrooxEngine.Slot, FrooxEngine.Slot)
   at FrooxEngine.SyncBagBase`2[[Elements.Core.RefID, Elements.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InternalRemove(Elements.Core.RefID, Boolean, Boolean)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.RelocateOrDestroyEmpty(System.Func`1<FrooxEngine.Slot>)
   at FrooxEngine.Slot.DestroyPreservingAssets(FrooxEngine.Slot, Boolean)
   at FrooxEngine.Slot.DestroyPreservingAssets()
   at FrooxEngine.SimpleUserSpawn.OnUserLeft(FrooxEngine.User)
   at FrooxEngine.World.RunWorldEvents()
   at FrooxEngine.World.RefreshStep()
   at FrooxEngine.World.Refresh()
   at FrooxEngine.WorldManager.UpdateStep()
   at FrooxEngine.WorldManager.RunUpdateLoop()
   at FrooxEngine.Engine.UpdateStep()
   at FrooxEngine.Engine.RunUpdateLoop()
   at FrooxEngine.StandaloneFrooxEngineRunner.UpdateLoop()
```
this was shortened and should still be available in the logs.

### To Reproduce

i didn't personaly see this happen but best case is:
- host a net 9 headless
- play one shots
- see it die

### Expected behavior

audio should not crash a headless that easy

### Resonite Version Number

Beta 2024.12.2.1188

### What Platforms does this occur on?

Windows

### Log Files

[CHARLIE - 2024.12.2.1188 - 2024-12-05 14_59_53.log](https://github.com/user-attachments/files/18023137/CHARLIE.-.2024.12.2.1188.-.2024-12-05.14_59_53.log)

### Reporters

charlie-san

**Comment by shiftyscales** [comment]
Where did you get that portion of an exception from @charlie-sans? I can not find it in the log file you uploaded. Are you certain you uploaded the right log file?

**Comment by charlie-sans** [comment]
> Where did you get that portion of an exception from [@charlie-sans](https://github.com/charlie-sans)? I can not find it in the log file you uploaded. Are you certain you uploaded the right log file?

i should have? 
though i did get that part from copying the terminal that i had the headless runnning in.
[CHARLIE - 2024.12.2.1188 - 2024-12-05 14_18_45.log](https://github.com/user-attachments/files/18030773/CHARLIE.-.2024.12.2.1188.-.2024-12-05.14_18_45.log)
[CHARLIE - 2024.12.2.1188 - 2024-12-05 14_59_53.log](https://github.com/user-attachments/files/18030771/CHARLIE.-.2024.12.2.1188.-.2024-12-05.14_59_53.log)
[CHARLIE - 2024.12.2.1188 - 2024-12-05 12_48_59.log](https://github.com/user-attachments/files/18030772/CHARLIE.-.2024.12.2.1188.-.2024-12-05.12_48_59.log)
just incase, here's all of the headless logs inside that folder including the one i sent.
