### ISSUE TITLE
ConvexHullHelper.ComputeHull Fatal error. System.AccessViolationException

### ISSUE THREAD

**Issue by bontebok** [Yellow-Dog-Man/Resonite-Issues#3322]
### Describe the bug?

Today at 6:12 AM UTC, Creator Jam's Hub world crashed. The crash itself was outside of the Resonite log and was found in the docker console logs for the server. The output from the console error is shown below along with the headless log.

We do know that at the time of the crash, the Convex Hull Brush (Aerogel) was being used (Resonite Essentials -> Tools -> Brushes -> Convex Hull Brushes), however we spent about 30 minutes attempting to reproduce the issue but were unable to cause another crash.

We also know that two additional factors may have been present - the world may have started a save operating at the exact moment of the crash (you can see the prior save was almost exactly 10 minutes before the crash and we autosave every 10 minutes) and a user recently joined the world and may still been spawning in. We don't know if these factors are related, but we attempted to reproduce the issue as well forcing many world saves and having users join the world, but were unsuccessful.

It is possible this is related to this crash #1908, however as that crash occurred in Mono, the stack trace is somewhat different.

### To Reproduce

We were unable to reproduce the crash.

### Expected behavior

The System.AccessViolationException should not occur in the ComputeHull method.

### Resonite Version Number

Beta 2024.12.2.1188 (.NET 9 Headless Client)

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Linux Headless

### Log Files

[headless - 2024.12.2.1188 - 2024-12-08 04_50_05.log](https://github.com/user-attachments/files/18051196/headless.-.2024.12.2.1188.-.2024-12-08.04_50_05.log)

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory
. This is often an indication that other memory is corrupt.
   at BepuPhysics.Collidables.ConvexHullHelper.ComputeHull(System.Span`1<System.Numerics.Vector3>, BepuUtilities.Memory.BufferPool, BepuPhysics.Collidables.HullData ByRef)
   at Elements.Assets.BepuMeshHelper.ComputeConvexHull(Elements.Assets.MeshX, BepuUtilities.Memory.BufferPool, System.Object, System.Action, BepuPhysics.Collidables.ConvexHull ByRef, Elements.Core.float3 ByRef)
   at FrooxEngine.ConvexHullData+<BuildData>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`2[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.ConvexHullData+<BuildData>d__3, FrooxEngine, Version=2024.12.2.1188, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`2[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.ConvexHullData+<BuildData>d__3, FrooxEngine, Version=2024.12.2.1188, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`2[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.ConvexHullData+<BuildData>d__3, FrooxEngine, Version=2024.12.2.1188, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at FrooxEngine.Asset+<>c__DisplayClass70_0.<RequestLock>b__0(FrooxEngine.IAsset)
   at FrooxEngine.Asset.ProcessLockRequestQueue()
   at FrooxEngine.Asset.ReleaseWriteLock(System.Object)
   at FrooxEngine.ProceduralAssetProvider`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunBackgroundAssetUpdate()
   at Elements.Core.WorkProcessor.ProcessQueue(ThreadWorker, System.Collections.Concurrent.ConcurrentQueue`1<System.Action>)
   at Elements.Core.WorkProcessor.JobWorker(ThreadWorker)
   at Elements.Core.WorkProcessor+ThreadWorker+<>c__DisplayClass19_0.<.ctor>b__0()
```

### Reporters

Users who helped reproduce the issue Dolari, StiefelJackal, Storm_Dpd, TheSpecterLemon Stellanora

**Comment by shiftyscales** [comment]
It seems highly likely to me this is likely the same underlying issue as your previous report #1908, @bontebok - as Frooxius previously highlighted there- we ideally need a saved copy of a mesh that causes this issue, or some means by which to produce one reliably.

**Comment by bontebok** [comment]
> It seems highly likely to me this is likely the same underlying issue as your previous report [#1908](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1908), [@bontebok](https://github.com/bontebok) - as Frooxius previously highlighted there- we ideally need a saved copy of a mesh that causes this issue, or some means by which to produce one reliably.

Unfortunately, as the convex hull brush was the only convex hull used during the crash - the exact mesh created from the brush was lost as it only exists in the in-memory data model. Based on interviews from the same crash that occurred during a .NET 9 test that occurred earlier in the week, a convex hull brush was used by Phant when headless crashed with the same exception.

It appears to be a race condition that is extremely difficult to replicate, and due to the nature of the crash, it will be impossible to recover the exact convex hull mesh from the data model as this exception occurs uncaught by FrooxEngine and no world is saved upon the crash.

**Comment by Frooxius** [comment]
Hmm this one is tricky issue. Without a replication case, this will be extremely difficult to diagnose, especially since it seems to occur only rarely.

Typically when we get case like this, we enable debugging mode for BEPUv2 which will track all the memory allocations and indicate where the problem occurs, but that requires having a repro case.

I don't think we can do much in this case without one.

If no new information doesn't come by, the best approach would be wait until we make the .NET 9 switch and then we sync up with upstream BEPUv2 for all its latest fixes and such.

**Comment by bontebok** [comment]
> Hmm this one is tricky issue. Without a replication case, this will be extremely difficult to diagnose, especially since it seems to occur only rarely.
> 
> Typically when we get case like this, we enable debugging mode for BEPUv2 which will track all the memory allocations and indicate where the problem occurs, but that requires having a repro case.

What do you think if I develop a mod that catches the exception and immediately saves the current data model? This would unfortunately have to wait until Harmony adds .NET 9 support as currently we do not have a method available to mod a headless, but once that is deployed I could quickly toss that together and be ready for the next time we crashed. Would capturing the data model at the moment of a crash be helpful since the Convex Hull Brush mesh data only exists in the data model?

**Comment by Frooxius** [comment]
@bontebok If you managed to dump the data model when that happens that could potentially help a lot - the problematic convex hull would already be in the data model, since the convex hull computation happens after that.

I see two potential problems with this though:
1) I'm aware there are some limitations on catching `System.AccessViolationException`, so I'm not sure if you actually can, but I haven't looked deeper into it: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-accessviolationexception
2) The memory might be corrupted at this point, but it's one of those "have to try it and see" things.

Question is though, how often does this actually happen?

**Comment by bontebok** [comment]
Thanks for the details, might still be worth a shot.

> Question is though, how often does this actually happen?

It only happens when a convex hull brush tool is being used or possibly a convex hull collider, so depending on the jam or build event, it could happen rarely or regularly. Some users love Convex Hull Brushes while others never use them.

The crash occured not even 15 minutes into the .NET 9 test Medra hosted last week. Phant came into the world and used a Convex Hull Brush Tool and promptly crashed the world. When I spoke to Phant, he was all too familiar with the crashes caused by this tool and likely was testing it with the intention of knowing if .NET 9 corrected for this. He stated due to the crashing, he no longer uses it and might even forbid its use in his sessions.

We crashed a second time when Dolari was using it to create ice cubes during the jam on Sunday. After that we gathered in another copy of the world and attempted like mad to reproduce it, but as you are aware, when you want something to happen, it never does.

Prior to those two events it had been a while since the last crash, but that's more than likely a result of little to no builders using the Convex Hull Brush. I remember them occuring more regularly in the past, but I also recall seeing more people using the Convex Hull Brush then as well.

**Comment by Redd56** [comment]
just realized since this was a headless/.net9 issue has anyone tested this on splitening yet? to see if its occuring there???

**Comment by mpmxyz** [comment]
I spent the last days debugging a user's world, created a replication item and found out it matches this and a few other issues:
#6221 #3322 #1908 #1198 #2213 #5915

Reproduction Item:
[Rock1.resonitepackage.zip](https://github.com/user-attachments/files/26632518/Rock1.resonitepackage.zip)

The following stderr output comes from Renderite.Host.
It has been intercepted using a modified Resonite.exe Bootstrapper:
```
Fatal error.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at BepuPhysics.Collidables.ConvexHullHelper.ComputeHull(System.Span`1<System.Numerics.Vector3>, BepuUtilities.Memory.BufferPool, BepuPhysics.Collidables.HullData ByRef)
   at Elements.Assets.BepuMeshHelper.ComputeConvexHull(Elements.Assets.MeshX, BepuUtilities.Memory.BufferPool, System.Object, System.Action, BepuPhysics.Collidables.ConvexHull ByRef, Elements.Core.float3 ByRef)
   at FrooxEngine.ConvexHullData+<BuildData>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FrooxEngine.ConvexHullData+<BuildData>d__3, FrooxEngine, Version=2026.4.9.1303, Culture=neutral, PublicKeyToken=null]](<BuildData>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.ValueTuple`2[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[FrooxEngine.ConvexHullData+<BuildData>d__3, FrooxEngine, Version=2026.4.9.1303, Culture=neutral, PublicKeyToken=null]](<BuildData>d__3 ByRef)
   at FrooxEngine.ConvexHullData.BuildData()
   at FrooxEngine.MeshPhysicsData`1+<<EnsureUpToDate>b__30_0>d[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.MeshPhysicsData`1+<<EnsureUpToDate>b__30_0>d[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], FrooxEngine, Version=2026.4.9.1303, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.MeshPhysicsData`1+<<EnsureUpToDate>b__30_0>d[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], FrooxEngine, Version=2026.4.9.1303, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FrooxEngine.MeshPhysicsData`1+<<EnsureUpToDate>b__30_0>d[[Elements.Assets.ConvexHullBepuData, Elements.Assets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], FrooxEngine, Version=2026.4.9.1303, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Elements.Core.WorkProcessor.ProcessQueue(ThreadWorker, System.Collections.Concurrent.ConcurrentQueue`1<System.Action>)
   at Elements.Core.WorkProcessor.JobWorker(ThreadWorker)
   at Elements.Core.WorkProcessor+ThreadWorker+<>c__DisplayClass19_0.<.ctor>b__0()
   at System.Threading.Thread.StartCallback()
```

**Comment by mpmxyz** [comment]
This is the point data that caused the issue:
[1.json](https://github.com/user-attachments/files/26645733/1.json)
The following program allows testing the issue without involving FrooxEngine:
```C#
using BepuUtilities.Memory;
using System.Numerics;
using BepuPhysics.Collidables;

namespace BepuPhysicsCrash;

class Programm {
    /// <summary>
    /// This struct is used to load the point data from the JSON file.
    /// </summary>
    internal struct Point
    {
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }

        public Point(float x, float y, float z)
        {
            X = x;
            Y = y;
            Z = z;
        }
        public Point(Vector3 v)
        {
            X = v.X;
            Y = v.Y;
            Z = v.Z;
        }
        public static implicit operator Vector3(Point p)
        {
            return new Vector3(p.X, p.Y, p.Z);
        }
    }

    static void Main()
    {
        foreach (var file in Environment.GetCommandLineArgs().Skip(1))
        {
            try
            {
                Console.WriteLine($"Trying file '{file}'...");
                using FileStream stream = File.OpenRead(file);
                var points = System.Text.Json.JsonSerializer.Deserialize<Point[]>(stream)!.Select(point => (Vector3)point).ToArray();
                using var pool = new BufferPool();
                ConvexHullHelper.ComputeHull(points, pool, out var hullData);
                Console.WriteLine($"Success with file '{file}': {hullData}");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error with file '{file}': {e?.ToString()}");
            }
        }
    }
}
```
