### ISSUE TITLE
WebSockets can crash the world with a high number of events at once

### ISSUE THREAD

**Issue by brecert** [Yellow-Dog-Man/Resonite-Issues#3365]
### Describe the bug?

High numbers of WebSocket events can cause world crashes with the following exception.
I've found the higher amount of events, the more likely a crash is to happen.
```
04:51:18.071 ( 89 FPS)	Unhandled Exception when updating world: brecert World. State Running, Refresh Stage: ProtoFluxEvents, Init State: Finished, SyncTick 2333, StateVersion: 4666
System.NullReferenceException: Object reference not set to an instance of an object
  at ProtoFlux.Runtimes.Execution.ExecutionEventDispatcher`1[C].DispatchEvents (ProtoFlux.Runtimes.Execution.ExecutionRuntime`1[C] runtime, C context) [0x0005b] in <61ca38d4407143769f23776638187968>:0 
  at FrooxEngine.ProtoFlux.ProtoFluxNodeGroup.RunNodeEvents () [0x00030] in <36535ea442c446bab5bb12cf1df1d043>:0 
  at FrooxEngine.ProtoFlux.ProtoFluxController.RunNodeEvents () [0x0002d] in <36535ea442c446bab5bb12cf1df1d043>:0 
  at FrooxEngine.World.RefreshStep () [0x00411] in <36535ea442c446bab5bb12cf1df1d043>:0 
  at FrooxEngine.World.Refresh () [0x00073] in <36535ea442c446bab5bb12cf1df1d043>:0 
  at FrooxEngine.WorldManager.UpdateStep () [0x004a3] in <36535ea442c446bab5bb12cf1df1d043>:0 
04:51:18.156 ( 89 FPS)	Exception when receiving websocket data from ws://localhost:7547/: Aborted
04:51:18.156 ( 89 FPS)	Closing Websocket client to ws://localhost:7547/
``` 

### To Reproduce

To test this I created a node script and used the library `ws` for the websocket server.

```js
import { WebSocketServer } from "ws";

const wss = new WebSocketServer({ port: 7547 });

setInterval(() =>
  wss.clients.forEach((c) => {
    for (let i = 0; i < 1000; i++) {
      c.send("text");
    }
  }), 10);
```

Within Resonite I spawned the following item, which is a basic WebSocket connection creator and event receiver. `resrec:///U-brecert/R-20391e04-1312-4d59-b1d5-5b50c48de4a2`
Note that the increment/data store is not necessary to cause the crash.

Run the spawned WebSocket to the node server, after a little while the world should world crash with the error.
It may take a little while to happen or it may happen right away, it's fairly random but I have found it to be more consistent by increasing the amount of messages sent.

### Expected behavior

No crash

### Resonite Version Number

Beta 2024.12.10.482

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive, Desktop

### Log Files

[NYMI - 2024.12.10.482 - 2024-12-16 04_49_53.log](https://github.com/user-attachments/files/18148204/NYMI.-.2024.12.10.482.-.2024-12-16.04_49_53.log)

### Additional Context

I encountered this while I was building a bluesky jetstream consumer for an interactive data visualization world, there were ~300-700 events per second on average and I was getting a world crash every 10ish minutes or so.

### Reporters

brecert

**Comment by bontebok** [comment]
I wonder if this is related to closed issue #19.

**Comment by stiefeljackal** [comment]
> I wonder if this is related to closed issue [#19](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/19).

Looking at the log file in #19, I see the same stacktrace from what was posted above in that log file too:

```
System.NullReferenceException: Object reference not set to an instance of an object
  at ProtoFlux.Runtimes.Execution.ExecutionEventDispatcher`1[C].DispatchEvents (ProtoFlux.Runtimes.Execution.ExecutionRuntime`1[C] runtime, C context) [0x0005b] in <712d67076f074428b34c21311dbc5def>:0 
  at FrooxEngine.ProtoFlux.ProtoFluxNodeGroup.RunNodeEvents () [0x00030] in <00f4a9dfdd854c0499371f5b3e237373>:0 
  at FrooxEngine.ProtoFlux.ProtoFluxController.RunNodeEvents () [0x0001c] in <00f4a9dfdd854c0499371f5b3e237373>:0 
  at FrooxEngine.World.RefreshStep () [0x003f4] in <00f4a9dfdd854c0499371f5b3e237373>:0 
  at FrooxEngine.World.Refresh () [0x00073] in <00f4a9dfdd854c0499371f5b3e237373>:0 
  at FrooxEngine.WorldManager.UpdateStep () [0x004a3] in <00f4a9dfdd854c0499371f5b3e237373>:0 
```

Perhaps something regressed or propped up again since the cause for that WebSocket issue was a race condition.

**Comment by OrionMoonclaw** [comment]
I encountered this crash on my phone headless as well, but it seemed to occur with websocket usage that was not excessive in any way, pretty much every couple of hours with events firing around once per second, so I tried the reproduction example above and it reliably causes a world crash almost immediately.

I had a look at the WebsocketClient class and noticed that events are fired directly from the loop with no synchronization, so I ended up wrapping it in RunSynchronously and that fixed the problem for me (see: https://codeberg.org/Orion_Moonclaw/PreventWebsocketCrash)

**Comment by Redd56** [comment]
Was just reading up on websocketsharp and realized it seems to be aiming for more of a unity focused design/older .net core design. not really a modern design. Do you think yall think it would be reasonable to swap it out with the built in websocket systems in .net10? or maybe a custom solution if needed or would that be too much of a burden do ya think.

**Comment by Frooxius** [comment]
This particular crash doesn't seem to be caused by websocketsharp.

**Comment by Frooxius** [comment]
Actually... we don't even use websocketsharp for this at all, it already uses the built-in websocket client.

**Comment by Redd56** [comment]
Ah. Good to know.

**Comment by Redd56** [comment]
Oh neat! Where is wss even used then cause i got no idea myself.

> Actually... we don't even use websocketsharp for this at all, it already uses the built-in websocket client.

**Comment by aaronvark** [comment]
It seems we're also seeing this crash in the current latest version. I am receiving a lot of separate text messages over a websocket connection (not ResoniteLink), and occasionally it will crash the world with the following error in Log:

```
❌14:26:58.250 (FPS: 60):	Unhandled Exception when updating world: R&D-Blanco_TEST. State Running, Refresh Stage: ProtoFluxEvents, Init State: Finished, SyncTick 86073, StateVersion: 172146
System.NullReferenceException: Object reference not set to an instance of an object.
   at FrooxEngine.ProtoFlux.ProtoFluxNodeGroup.RunNodeEvents() in /home/runner/work/FrooxEngine/FrooxEngine/FrooxEngine/FrooxEngine/ProtoFlux/ProtoFluxNodeGroup.cs:line 607
   at FrooxEngine.ProtoFlux.ProtoFluxController.RunNodeEvents() in /home/runner/work/FrooxEngine/FrooxEngine/FrooxEngine/FrooxEngine/ProtoFlux/ProtoFluxController.cs:line 335
   at FrooxEngine.World.RefreshStep() in /home/runner/work/FrooxEngine/FrooxEngine/FrooxEngine/FrooxEngine/World.cs:line 1791
   at FrooxEngine.World.Refresh() in /home/runner/work/FrooxEngine/FrooxEngine/FrooxEngine/FrooxEngine/World.cs:line 1428
   at FrooxEngine.WorldManager.UpdateStep() in /home/runner/work/FrooxEngine/FrooxEngine/FrooxEngine/FrooxEngine/WorldManager.cs:line 616
```

This is the script on the Resonite side:

<img width="3628" height="1305" alt="Image" src="https://github.com/user-attachments/assets/4d9efe2a-ff9f-4850-8ae5-e8e4fd58d7f4" />

And how we're sending it from C#:

<img width="1250" height="783" alt="Image" src="https://github.com/user-attachments/assets/92d248f6-d62c-4f02-90db-55661aa77683" />

We've considered reducing the number of messages and parsing them as a giant dump, or moving to ResoniteLink for the implementation of this logic, but if it's possible to fix this issue that would be ideal.

**Comment by aaronvark** [comment]
Did another test today sending at 60FPS with 1ms delay for 4 "users", having bundled all the bones into a single msg per user, and it still crashed after like 5-10m. Will be doing another test tomorrow at 30FPS with 2ms delay between users, and see how that goes.

**Comment by Frooxius** [comment]
If you're getting crashes still, please share logs. Otherwise this is hard to action on our end.

**Comment by brecert** [comment]
Since it's been nearly two years I decided to test it again. The world still instantly world crashes after connecting to the server.

[Chiih - 2026.8.5.1169 - 2026-08-06 12_04_28.log](https://github.com/user-attachments/files/30796553/Chiih.-.2026.8.5.1169.-.2026-08-06.12_04_28.log)
